name: Run Automated Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Environment
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'

      - name: Dependencies
        run: |
          echo "Installing Dependencies..."
          npm install

      - name: Run Automated Tests
        run: |
          npm run cy:run:env1

      - name: Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test_report
          path: |
            cucumber-report.html  
            cypress/screenshots/
            results/
          retention-days: 7
          overwrite: true
